import { Crimson_Pro } from "next/font/google";
import { StackProvider, StackTheme } from "@stackframe/stack";
import { stackServerApp } from "../stack";
import "./globals.css";
import { ConvexClientProvider } from "./ConvexClientProvider";
import Provider from "./provider";

const crimsonPro = Crimson_Pro({
  variable: "--font-crimson-pro",
  subsets: ["latin"],
  weight: ["200", "300", "400", "500", "600", "700"], // Add weights you want
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${crimsonPro.variable} antialiased`}
      ><StackProvider app={stackServerApp}><StackTheme>
        <ConvexClientProvider>
          <Provider>
            {children}
          </Provider>
        </ConvexClientProvider>
       </StackTheme></StackProvider></body>
    </html>
  );
}